version: '3.8'

services:
  api:
    image: igpal/sbp-api:latest
    ports:
      - 5000:5000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: always
    logging:
      driver: json-file
      options:
        'max-size': '10m'
        'max-file': '5'
